---

- name: Create sysadmin group
  group:
    name: sysadmin
    state: present
  become: true

- name: Add sysadmin to the sudoers
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sysadmin'
    line: '%sysadmin ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s
  become: true

- name: Add or update users
  user:
    name: "{{ item.name }}"
    groups: "{{ item.groups | default([]) }}"
    move_home: yes
    create_home: yes
    shell: "/bin/bash"
    state: present
  loop: "{{ users }}"
  when: item.remove is not defined or not item.remove
  become: true

- name: Set authorized key for user
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', item.authorized_key) }}"
  loop: "{{ users }}"
  when: item.authorized_key is defined and not (item.remove | default(false)) and (item.authorized_key | is_file)
  become: true

- name: Remove users
  user:
    name: "{{ item.name }}"
    state: absent
    remove: "{{ item.remove_home | default(false) }}"
  loop: "{{ users }}"
  when: item.remove | default(false)
  become: true