{
 "title": "Weather Station",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "radius", "label": "anometer radius", "query": "8" },
   { "name": "angle_corr", "label": "Correcçao de angulo", "query": "0" },
   { "name": "rate", "query": "30s,1m,5m,10m,15m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "fatcloud-windrose-panel",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "((irate(anemometer_rpm[30s]) * 2 * 3.14 * $radius)/100)",
     "legendFormat": "speed"
    },
    {
     "expr": "(rose_direction*(360/96) + $angle_corr) % 360",
     "legendFormat": "direction"
    }
   ]
  },
  {
   "title": "Direction",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rose_direction*(360/96) + $angle_corr) % 360"
    }
   ]
  },
  {
   "title": "Direction",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rose_direction*(360/96) + $angle_corr) % 360"
    }
   ]
  },
  {
   "title": "Temperatura Vs Ontem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature_3xx - (temperature_3xx offset 1d)"
    }
   ]
  },
  {
   "title": "Direcção Actual",
   "type": "fatcloud-windrose-panel",
   "gridPos": { "h": 14, "w": 6, "x": 6, "y": 3 },
   "targets": [
    {
     "expr": "((irate(anemometer_rpm[30s])* 2 * 3.14 * $radius)/100)",
     "legendFormat": "speed"
    },
    {
     "expr": "(rose_direction*(360/96) + $angle_corr) % 360",
     "legendFormat": "direction"
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "uv_index" }
   ]
  },
  {
   "title": "Temperature Cº",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "temperature_bme280" }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "humidity_bme280" }
   ]
  },
  {
   "title": "Pressure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "mbar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pressure_3xx" }
   ]
  },
  {
   "title": "Temperature Cº",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "temperature_bme280", "legendFormat": "externa_280" }
   ]
  },
  {
   "title": "Wind",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((irate(anemometer_rpm[30s])* 2 * 3.14 * $radius)/100)*3.6"
    }
   ]
  },
  {
   "title": "Anometro RPM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "irate(anemometer_rpm[$rate])" }
   ]
  },
  {
   "title": "UV Index",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "uv_index != 0", "legendFormat": "uv_index" },
    { "expr": "(uvb_count * 0.002591)/2 != 0", "legendFormat": "uvb" },
    { "expr": "(uva_count * 0.001461)/2 !=0", "legendFormat": "uva" }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "yaxes": [
    { "format": "velocitykmh" }
   ],
   "targets": [
    {
     "expr": "((rate(anemometer_rpm[$rate])* 2 * 3.14 * $radius)/100)*3.6",
     "legendFormat": "media"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "mbar" } },
   "yaxes": [
    { "format": "mbar" }
   ],
   "targets": [
    { "expr": "pressure_3xx", "legendFormat": "externa_3xx" },
    { "expr": "pressure_bme280", "legendFormat": "externa_280" }
   ]
  },
  {
   "title": "Humidade",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    { "expr": "humidity_bme280", "legendFormat": "externa_280" }
   ]
  }
 ]
}