---
- hosts: all
  gather_facts: true
  become: true
  roles:
    - role: host/install_packages
      install_packages:
        - tar
        - unzip
        - git
        - python3
        - python3-pip
        - curl
        - cifs-utils
      install_pip_modules:
        - jmespath
        - netaddr
        - jinja2-ansible-filters

    - role: host/manage_users
      users:
        - name: "{{ lookup('env', 'USER') }}"
          authorized_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
          groups: |
            {{ [ 'sysadmin'] +
              ([] if ansible_architecture == "armv6l" else [ "docker" ] )
            }}
          remove: false
          remove_home: false

    - role: host/manage_volumes
      volumes: "{{ host_volumes | default([]) }}"
  
    - role: host/static_ip
      network_static_ip:   
        - interface: "{{ static_address.inteface | default('eth0') }}"
          addresses: 
            - "{{ static_address.inteface_address | ansible.netcommon.ipaddr('address/prefix') }}"
          gateway: "{{ static_address.gateway_address | ipaddr('address') }}"
          dns:
            - 8.8.8.8
            - 8.8.4.4
      when: static_address is defined
      
- hosts: all
  gather_facts: true
  become: true
  roles:
    - role: host_services/docker 
      when: ansible_architecture != "armv6l"

    - role: host_services/samba
      samba_shares: "{{ samba_share | default({}) }}"
      when: samba_share is defined

