---
- hosts: network_manager
  gather_facts: true
  become: true
  roles:
    - role: host/services/pi_hole
      network_interface: "{{ static_address.inteface | default('eth0') }}"
      vodafone_box: 
        box_mac_address: "D0:6E:DE:E2:69:73"
        gateway_address: "{{ vodafone.gateway_address | ansible.netcommon.ipaddr('address') }}"

      dhcp:
        ACTIVE: true
        START: "{{ static_address.gateway_address | ansible.netcommon.ipaddr('first_usable') }}"
        END: "{{ static_address.gateway_address | ansible.netcommon.ipaddr('last_usable') }}"
        ROUTER: "{{ static_address.gateway_address | ansible.netcommon.ipaddr('address') }}"
        LEASETIME: 24
        IPv6: false
        rapid_commit: false
      dns:
        - 127.0.0.1#5335