---
- hosts: vpn
  gather_facts: false
  become: true
  tags: vpn
  roles:
    - role: host_services/openvpn
      openvpn:
        protocol: "{{ openvpn_protocol | default('udp') }}"
        address: "{{ openvpn_address }}"
        port: "{{ openvpn_port | default(1194) }}"
        network_inteface: "{{ network_inteface }}" 
        dns: "{{ openvpn_dns | default(['8.8.8.8']) }}" 
        subnets:
          - "{{ network_gateway_address | ansible.netcommon.ipaddr('network/prefix') }}"
        clients: "{{ openvpn_clients | default([]) }}"
        revoke: "{{ openvpn_revoke | default([]) }}"
