---
- hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: host/install_packages
      packages:
        install:
          - open-iscsi

- name: install k3s
  #import_playbook: ../k3s-ansible/reset.yml
  import_playbook: ../k3s-ansible/site.yml
