---
- hosts: all
  gather_facts: false
  become: false
  roles:
    - role: host_services/node_exporter

- hosts: monitoring
  gather_facts: true
  become: true
  roles:
    - role: host_services/prometheus
      scrapers: "{{ prometheus_extra_scrapes | default({}) }}"
    - role: host_services/grafana
