---
- hosts: media_server
  gather_facts: true
  become: true
  roles:

    - role: docker_instances/plex_server
      claim: "{{ plex.location.claim | default('') }}"
      plex_config_directory: "{{ plex.location.plex_configs | default('/etc/docker/plex') }}"
      tautulli_config_directory: "{{ plex.location.tautulli_configs | default('/etc/docker/tautulli') }}"
      media_directory: "{{ plex.location.media }}"
      when: plex is defined

    - role: docker_instances/rutorrent
      download_directory: "{{ ru_torrent.location.download }}"
      configuration_directory: "{{ ru_torrent.location.config | default('/etc/docker/ru_torrent') }}"
      when: ru_torrent is defined

    - role: docker_instances/medusa
      medusa_config_directory: "{{ medusa.location.config | default('/etc/docker/medusa') }}"
      medusa_media_base_directory: "{{ medusa.location.media }}"
      medusa_downloads:
        incoming: "{{ medusa.location.media }}/downloads/shows-incoming"
        finish: "{{ medusa.location.media }}/downloads/shows-finish"
      medusa_media:
        shows_directory: "{{ medusa.location.media }}/media/shows"
        shows_anime_directory: "{{ medusa.location.media }}/media/shows-anime"
      when: medusa is defined

    - role: docker_instances/couchpotato
      couchpotato_config_directory: "{{ couchpotato.location.config | default('/etc/docker/couchpotato') }}"
      couchpotato_media_base_directory: "{{ couchpotato.location.media }}"    
      when: couchpotato is defined
