---
- hosts: all
  gather_facts: true
  become: true
  roles:
    - role: host/packages
      packages:
        key:
          add: []
          remove: []
        repository:
          add: []
          remove: []
        remove: []
#       - cifs-utils
        install:
        - tar
        - unzip
        - git
        - curl
        - cifs-utils

        - apt-transport-https
        - ca-certificates
        - gnupg
        - lsb-release

        - python3
        - python3-pip
    - role: python/pip
      pip:
        remove: []
        install:
        - jmespath
        - netaddr
        - jinja2-ansible-filters

#    - role: host/users
#      users:
#        - name: "{{ lookup('env', 'USER') }}"
#          authorized_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"
#          append_group: yes
#          groups: 
#            - sysadmin
#          remove: false
#          remove_home: false

    - role: host/volumes
      when: volumes is defined

    - role: host/network/static_address
      network:
        static_address:
          - interface: "{{ static_address.inteface | default('eth0') }}"
            addresses: 
              - "{{ static_address.inteface_address | ansible.netcommon.ipaddr('address/prefix') }}"
            gateway: "{{ static_address.gateway_address | ipaddr('address') }}"
            dns:
              - 8.8.8.8
              - 8.8.4.4
      when: static_address is defined

- hosts: docker
  gather_facts: true
  become: true
  roles:
    - role: host/services/docker

    - role: host/users
      users:
      - name: "{{ lookup('env', 'USER') }}"
        append_group: yes
        groups: 
          - docker
