---
- hosts: media-center
  gather_facts: true
  become: true
  roles:
    - role: util/git/get_grafana_labs_application
      project_name: prometheus
      repo_url: https://api.github.com/repos/prometheus/prometheus/releases/latest
      binary_path: /opt/prometheus/prometheus

    - role: util/git/get_grafana_labs_application
      project_name: node_exporter
      repo_url: https://api.github.com/repos/prometheus/node_exporter/releases/latest
      binary_path: /opt/node_exporter/node_exporter

    - role: util/git/get_grafana_labs_application
      project_name: loki
      repo_url: https://api.github.com/repos/grafana/loki/releases/latest
      binary_path: /opt/loki/loki-linux-{{ architecture_index[ansible_architecture] }}

    - role: util/git/get_grafana_labs_application
      project_name: promtail
      repo_url: https://api.github.com/repos/grafana/loki/releases/latest
      binary_path: /opt/promtail/promtail-linux-{{ architecture_index[ansible_architecture] }}
