---
- name: Install promtail
  import_role:
    name: util/git/get_grafana_labs_application
  vars:
    project_name: promtail
    repo_url: https://api.github.com/repos/grafana/loki/releases/latest
    binary_path: /opt/promtail/promtail-linux-{{ architecture_index[ansible_architecture] }}
    architecture_index:
      x86_64: amd64
      armv7l: arm
      armv6l: arm
      aarch64: arm64

- name: Create config directory
  ansible.builtin.file:
    path: /etc/opt/promtail
    state: directory

- name: Set configs
  template: 
    src: promtail-config.yml.j2
    dest: /etc/opt/promtail/promtail-config.yml
    backup: yes
  notify:
    - service.restart.promtail

- name: Add promtail as a service
  import_role:
    name: host/manage_services
  vars:
    services:
      promtail:
        Unit:
          Description: Node Metrics Service
        Service:
          ExecStart: "/opt/promtail/promtail-linux-{{ architecture_index[ansible_architecture] }} --config.file=/etc/opt/promtail/promtail-config.yml"
        Install:
          WantedBy: multi-user.target
  register: servie_register

- name: Activate promtail
  systemd:
    name: promtail
    state: started
    enabled: yes
    masked: no
  