---
- name: Install Samba
  apt:
    name: "{{ samba_packages }}"
    state: latest
    update_cache: yes

- name: Copy the Customize smb.conf file
  template: 
    src: etc_samba_smb.conf.j2
    dest: /etc/samba/smb.conf
    backup: yes
  notify:
    - samba.restart