---
- name: Change volume state
  mount:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    fstype: "{{ item.fstype }}"
    state: "{{ item.state | default('mounted') }}"
    opts: "{{ item.opts | default(omit) }}"
  loop: "{{ volumes }}"
  when: mount_info.changed or (item.state | default("mounted")) != "mounted"
