---
- name: Install Node exporter
  import_role:
    name: util/git/get_grafana_labs_application
  vars:
    project_name: node_exporter
    repo_url: https://api.github.com/repos/prometheus/node_exporter/releases/latest
    binary_path: "{{ node_exporter_bin_path }}"

- name: Add Node exporter as a service
  import_role:
    name: host/manage_services
  vars:
    services:
      node_exporter:
        Unit:
          Description: Node Metrics Service
        Service:
          #EnvironmentFile: /etc/sysconfig/node_exporter
          ExecStart: "{{ node_exporter_bin_path }} $OPTIONS"
        Install:
          WantedBy: multi-user.target
  register: servie_register

- name: Activate node_exporter
  systemd:
    name: node_exporter
    state: started
    enabled: yes
    masked: no
  