---
- name: get "{{ item }}" status
  stat:
    path: "{{ easy_rsa_pki_dir }}/issued/{{ item }}.crt"
  register: file_info

- name: generate certificate for "{{ item }}"
  shell: "{{ easy_rsa_dir }}/easyrsa build-client-full '{{ item }}' nopass"
  when: not file_info.stat.exists

- name: Copy template to remote machine
  copy:
    src: "client.ovpn.j2"
    dest: /tmp/client.ovpn.j2

- name: Generate opvn file for "{{ item }}"
  remote_template:
    template: /tmp/client.ovpn.j2
    path: "{{ openvpn_client_directory }}/{{ item }}.ovpn"
    vars:
      user: "{{ item }}"
