- name: Install required dependencies 
  apt:
    name: 
        - openvpn
        - easy-rsa
        - openssl 
        - ca-certificates
    state: latest
    update_cache: yes

## openvpn_easy_rsa_url: https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.8/EasyRSA-3.0.8.tgz

- name: check easy-rsa dir
  stat:
    path: "{{ easy_rsa_dir }}"
  register: file_stats

- name: Set easy-rsa dir
  shell: "make-cadir {{ easy_rsa_dir }}"
  when: not file_stats.stat.exists

- name: generate configs
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: vars.j2
      dest: "{{ easy_rsa_dir }}/vars"

    - src: server.conf.j2
      dest: "{{openvpn_server_directory }}/server.conf"

    - src: client-common.txt.j2
      dest: "{{openvpn_server_directory }}/client-common.txt"

  notify: service.restart.openvpn

- name: Check and generate required files
  include_tasks: check_run.yml
  loop: 
    - file: "{{ easy_rsa_pki_dir }}"
      command: "{{ easy_rsa_dir }}/easyrsa init-pki"

    - file: "{{ easy_rsa_pki_dir }}/ca.crt"
      command: "{{ easy_rsa_dir }}/easyrsa --batch build-ca nopass"

    - file: "{{ easy_rsa_pki_dir }}/dh.pem"
      command: "{{ easy_rsa_dir }}/easyrsa gen-dh"

    - file: "{{ easy_rsa_pki_dir }}/crl.pem"
      command: "{{ easy_rsa_dir }}/easyrsa gen-crl"

    - file: "{{ easy_rsa_pki_dir }}/issued/server.crt"
      command: "{{ easy_rsa_dir }}/easyrsa build-server-full server nopass"

    - file: "{{ easy_rsa_pki_dir }}/tc.key"
      command: openvpn --genkey --secret {{ easy_rsa_pki_dir }}/tc.key

- name: move files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0600' 
    remote_src: true
  loop:
    - src: "{{ easy_rsa_pki_dir }}/ca.crt"
      dest: "{{openvpn_server_directory }}/ca.crt"
    - src: "{{ easy_rsa_pki_dir }}/private/ca.key"
      dest: "{{openvpn_server_directory }}/ca.key"
    - src: "{{ easy_rsa_pki_dir }}/issued/server.crt"
      dest: "{{openvpn_server_directory }}/server.crt"
    - src: "{{ easy_rsa_pki_dir }}/private/server.key"
      dest: "{{openvpn_server_directory }}/server.key"
    - src: "{{ easy_rsa_pki_dir }}/tc.key"
      dest: "{{openvpn_server_directory }}/tc.key"
    - src: "{{ easy_rsa_pki_dir }}/dh.pem"
      dest: "{{openvpn_server_directory }}/dh.pem"
  notify: service.restart.openvpn

- name: move files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ openvpn_user }}"
    group: "{{ openvpn_group }}"
    mode: '0644' 
    remote_src: true
  loop:
    - src: "{{ easy_rsa_pki_dir }}/crl.pem"
      dest: "{{ openvpn_server_directory }}/crl.pem"
  notify: service.restart.openvpn

- name: enable net.ipv4.ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Set firewall rules
  include_tasks: set_firewall_rules.yml

- name: Activate openvpn-server
  systemd:
    name: openvpn-server@server.service
    state: started
    enabled: yes
    masked: no
  
- name: generate clients files
  include_tasks: generate_clients.yml
  loop: "{{ openvpn.clients | default([]) }}"

- name: revoke clients
  include_tasks: revoke_clients.yml
  loop: "{{ openvpn.revoke }}"
