---
- name: Install Prometheus
  import_role:
    name: util/git/get_grafana_labs_application
  vars:
    project_name: prometheus
    repo_url: https://api.github.com/repos/prometheus/prometheus/releases/latest
    binary_path: /opt/prometheus/prometheus

- name: Add Prometheus as a service
  import_role:
    name: host/manage_services
  vars:
    services:
      prometheus:
        Unit:
          Description: Prometheus Server
          Documentation: https://prometheus.io/docs/introduction/overview/
          After: network-online.target
        Service:
          ExecStart: "/opt/prometheus/prometheus --config.file=/etc/opt/prometheus/prometheus.yml --storage.tsdb.path=/opt/prometheus/data"
          Restart: on-failure
        Install:
          WantedBy: multi-user.target
  register: servie_register

- name: Set scrappets
  template: 
    src: prometheus.yml.j2
    dest: /etc/opt/prometheus/prometheus.yml
    backup: yes
  notify:
    - service.restart.prometheus

- name: Activate prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes
    masked: no
  